import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";

const cairo= Cairo({
  subsets: ['arabic'],
  weight: ['400','600','700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={cairo.className}
      >
        {children}
      </body>
    </html>
  );
}
